//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPlus_Next.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabelPlus_Next.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于(_A) 的本地化字符串。
        /// </summary>
        public static string aboutAToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutAToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string button_OK {
            get {
                return ResourceManager.GetString("button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        public static string button_output {
            get {
                return ResourceManager.GetString("button_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string button_start {
            get {
                return ResourceManager.GetString("button_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string button_yes {
            get {
                return ResourceManager.GetString("button_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string buttonAbort {
            get {
                return ResourceManager.GetString("buttonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法输出文件： 的本地化字符串。
        /// </summary>
        public static string can_not_output_file {
            get {
                return ResourceManager.GetString("can_not_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据标号分组,执行指定动作组中的动作GroupN 的本地化字符串。
        /// </summary>
        public static string checkBoxAutoGroupAction {
            get {
                return ResourceManager.GetString("checkBoxAutoGroupAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过无标号图 的本地化字符串。
        /// </summary>
        public static string checkBoxJumpNoNum {
            get {
                return ResourceManager.GetString("checkBoxJumpNoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理无标号文档 的本地化字符串。
        /// </summary>
        public static string checkBoxMakeUnLabeledFile {
            get {
                return ResourceManager.GetString("checkBoxMakeUnLabeledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义字体 的本地化字符串。
        /// </summary>
        public static string checkBoxSetFont {
            get {
                return ResourceManager.GetString("checkBoxSetFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义字号 的本地化字符串。
        /// </summary>
        public static string checkBoxSetFontSize {
            get {
                return ResourceManager.GetString("checkBoxSetFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用指定类型图源 的本地化字符串。
        /// </summary>
        public static string checkBoxUseOtherFileType {
            get {
                return ResourceManager.GetString("checkBoxUseOtherFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除所有标签吗！？ 的本地化字符串。
        /// </summary>
        public static string clear_all_label_question {
            get {
                return ResourceManager.GetString("clear_all_label_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译 的本地化字符串。
        /// </summary>
        public static string default_file_name {
            get {
                return ResourceManager.GetString("default_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件StartBlocks丢失 的本地化字符串。
        /// </summary>
        public static string error_file_startblocks_lost {
            get {
                return ResourceManager.GetString("error_file_startblocks_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件版本太高，无法使用本版本编辑！ 的本地化字符串。
        /// </summary>
        public static string error_file_version_over {
            get {
                return ResourceManager.GetString("error_file_version_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件失败 的本地化字符串。
        /// </summary>
        public static string error_openfilefail {
            get {
                return ResourceManager.GetString("error_openfilefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(_E) 的本地化字符串。
        /// </summary>
        public static string exitEToolStripMenuItem {
            get {
                return ResourceManager.GetString("exitEToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件设置 的本地化字符串。
        /// </summary>
        public static string FileSettingFrm_Text {
            get {
                return ResourceManager.GetString("FileSettingFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string fileToolStripLabel {
            get {
                return ResourceManager.GetString("fileToolStripLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(_F) 的本地化字符串。
        /// </summary>
        public static string fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        public static string helpAToolStripMenuItem {
            get {
                return ResourceManager.GetString("helpAToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出带标记图片 的本地化字符串。
        /// </summary>
        public static string ImageOutputFrm_Text {
            get {
                return ResourceManager.GetString("ImageOutputFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片管理(_I) 的本地化字符串。
        /// </summary>
        public static string imageToolStripMenuItem {
            get {
                return ResourceManager.GetString("imageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件未保存，请先将文件存至与图片同文件夹下！ 的本地化字符串。
        /// </summary>
        public static string input_images_need_save {
            get {
                return ResourceManager.GetString("input_images_need_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程及自动化 的本地化字符串。
        /// </summary>
        public static string labelAutodoTip {
            get {
                return ResourceManager.GetString("labelAutodoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (动作组名) 的本地化字符串。
        /// </summary>
        public static string labelAutoGroupActionTip {
            get {
                return ResourceManager.GetString("labelAutoGroupActionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string labelComment {
            get {
                return ResourceManager.GetString("labelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换条目(Ctrl+Enter,),快捷短语(Alt+A) 的本地化字符串。
        /// </summary>
        public static string labelCtrlEnterTip {
            get {
                return ResourceManager.GetString("labelCtrlEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认格式 的本地化字符串。
        /// </summary>
        public static string labelDefaultFormatTip {
            get {
                return ResourceManager.GetString("labelDefaultFormatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略文件 的本地化字符串。
        /// </summary>
        public static string labelFolderFile {
            get {
                return ResourceManager.GetString("labelFolderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组设置 的本地化字符串。
        /// </summary>
        public static string labelGroup {
            get {
                return ResourceManager.GetString("labelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含文件 的本地化字符串。
        /// </summary>
        public static string labelIncludedFile {
            get {
                return ResourceManager.GetString("labelIncludedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出标号(1、2、3…) 的本地化字符串。
        /// </summary>
        public static string LabelNumCheckBox {
            get {
                return ResourceManager.GetString("LabelNumCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出格式 的本地化字符串。
        /// </summary>
        public static string labelOutputFormat {
            get {
                return ResourceManager.GetString("labelOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出项目 的本地化字符串。
        /// </summary>
        public static string labelOutputItemTip {
            get {
                return ResourceManager.GetString("labelOutputItemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放比例 的本地化字符串。
        /// </summary>
        public static string labelZoom {
            get {
                return ResourceManager.GetString("labelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string languageblock {
            get {
                return ResourceManager.GetString("languageblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(_D) 的本地化字符串。
        /// </summary>
        public static string listview_menustrip_del {
            get {
                return ResourceManager.GetString("listview_menustrip_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片管理 的本地化字符串。
        /// </summary>
        public static string ManageImageFrm_Text {
            get {
                return ResourceManager.GetString("ManageImageFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建翻译(_N) 的本地化字符串。
        /// </summary>
        public static string newToolStripMenuItem {
            get {
                return ResourceManager.GetString("newToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不要在编辑后关闭此文件 的本地化字符串。
        /// </summary>
        public static string notCloseFileCheckBox {
            get {
                return ResourceManager.GetString("notCloseFileCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加头尾标志(startN、endN)  的本地化字符串。
        /// </summary>
        public static string notHeadFootSignCheckBox {
            get {
                return ResourceManager.GetString("notHeadFootSignCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加头尾标志(startN、endN) 以便使用动作 的本地化字符串。
        /// </summary>
        public static string notLabelNumCheckBox {
            get {
                return ResourceManager.GetString("notLabelNumCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开翻译(_O) 的本地化字符串。
        /// </summary>
        public static string openToolStripMenuItem {
            get {
                return ResourceManager.GetString("openToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出已终止 的本地化字符串。
        /// </summary>
        public static string output_aborted {
            get {
                return ResourceManager.GetString("output_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出完毕 的本地化字符串。
        /// </summary>
        public static string output_complete {
            get {
                return ResourceManager.GetString("output_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出失败 的本地化字符串。
        /// </summary>
        public static string output_fail {
            get {
                return ResourceManager.GetString("output_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出带标记图片(_O) 的本地化字符串。
        /// </summary>
        public static string outputAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string outputButton {
            get {
                return ResourceManager.GetString("outputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Photoshop脚本(_P) 的本地化字符串。
        /// </summary>
        public static string outputPhotoshopScriptToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputPhotoshopScriptToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(_O) 的本地化字符串。
        /// </summary>
        public static string outputPToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputPToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出PS脚本 的本地化字符串。
        /// </summary>
        public static string OutputScriptFrm_Text {
            get {
                return ResourceManager.GetString("OutputScriptFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成成功 脚本文件已保存在同一目录下：auto_label_for_photoshop.jsx \n 使用方法：1.直接拖进Photoshop中；或&quot;文件-脚本-浏览&quot;，选中脚本 \n2.选择图片所在目录 的本地化字符串。
        /// </summary>
        public static string ps_output_complete {
            get {
                return ResourceManager.GetString("ps_output_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string save_complete {
            get {
                return ResourceManager.GetString("save_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件已修改，是否保存？ 的本地化字符串。
        /// </summary>
        public static string save_question {
            get {
                return ResourceManager.GetString("save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译另存为(_S) 的本地化字符串。
        /// </summary>
        public static string saveAsDToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveAsDToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存翻译(_S) 的本地化字符串。
        /// </summary>
        public static string saveProjectSToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveProjectSToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择图片文件夹。\n程序将为您在目录下自动创建翻译文本文件。 的本地化字符串。
        /// </summary>
        public static string tip_chose_photo_dir {
            get {
                return ResourceManager.GetString("tip_chose_photo_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件已保存为：{0} 的本地化字符串。
        /// </summary>
        public static string tip_new_file_be_saved {
            get {
                return ResourceManager.GetString("tip_new_file_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注里不能以&apos;-&apos;作为单独一行 的本地化字符串。
        /// </summary>
        public static string tip_setting_comment {
            get {
                return ResourceManager.GetString("tip_setting_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请以正确的格式设置分组，每行一组，分组数量为1-9组 的本地化字符串。
        /// </summary>
        public static string tip_setting_group {
            get {
                return ResourceManager.GetString("tip_setting_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除选中的标签吗? 的本地化字符串。
        /// </summary>
        public static string tip_sure_del_label {
            get {
                return ResourceManager.GetString("tip_sure_del_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览模式(_Q) 的本地化字符串。
        /// </summary>
        public static string toolStripButton_BrowseMode {
            get {
                return ResourceManager.GetString("toolStripButton_BrowseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审校模式(_R) 的本地化字符串。
        /// </summary>
        public static string toolStripButton_CheckMode {
            get {
                return ResourceManager.GetString("toolStripButton_CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▲ 字体增大 的本地化字符串。
        /// </summary>
        public static string toolStripButton_EditBig {
            get {
                return ResourceManager.GetString("toolStripButton_EditBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label模式(_W) 的本地化字符串。
        /// </summary>
        public static string toolStripButton_EditLabelMode {
            get {
                return ResourceManager.GetString("toolStripButton_EditLabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ▼ 字体减小 的本地化字符串。
        /// </summary>
        public static string toolStripButton_EditSmall {
            get {
                return ResourceManager.GetString("toolStripButton_EditSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件设置 的本地化字符串。
        /// </summary>
        public static string toolStripButton_FileSetting {
            get {
                return ResourceManager.GetString("toolStripButton_FileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏窗口(_T) 的本地化字符串。
        /// </summary>
        public static string toolStripButton_HideWindow {
            get {
                return ResourceManager.GetString("toolStripButton_HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录入模式(_E) 的本地化字符串。
        /// </summary>
        public static string toolStripButton_InputMode {
            get {
                return ResourceManager.GetString("toolStripButton_InputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 框内 的本地化字符串。
        /// </summary>
        public static string toolStripButton_zoomIn {
            get {
                return ResourceManager.GetString("toolStripButton_zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 框外 的本地化字符串。
        /// </summary>
        public static string toolStripButton_zoomOut {
            get {
                return ResourceManager.GetString("toolStripButton_zoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字键设置分类 的本地化字符串。
        /// </summary>
        public static string toolStripLabelTipSetCategory {
            get {
                return ResourceManager.GetString("toolStripLabelTipSetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示帮助(_H) 的本地化字符串。
        /// </summary>
        public static string viewHelpHToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewHelpHToolStripMenuItem", resourceCulture);
            }
        }
    }
}
