//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelPlus_Next.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabelPlus_Next.Lang.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于(_A).
        /// </summary>
        public static string aboutAToolStripMenuItem {
            get {
                return ResourceManager.GetString("aboutAToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        public static string button_OK {
            get {
                return ResourceManager.GetString("button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        public static string button_output {
            get {
                return ResourceManager.GetString("button_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        public static string button_start {
            get {
                return ResourceManager.GetString("button_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string button_yes {
            get {
                return ResourceManager.GetString("button_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        public static string buttonAbort {
            get {
                return ResourceManager.GetString("buttonAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法输出文件：.
        /// </summary>
        public static string can_not_output_file {
            get {
                return ResourceManager.GetString("can_not_output_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据标号分组,执行指定动作组中的动作GroupN.
        /// </summary>
        public static string checkBoxAutoGroupAction {
            get {
                return ResourceManager.GetString("checkBoxAutoGroupAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳过无标号图.
        /// </summary>
        public static string checkBoxJumpNoNum {
            get {
                return ResourceManager.GetString("checkBoxJumpNoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理无标号文档.
        /// </summary>
        public static string checkBoxMakeUnLabeledFile {
            get {
                return ResourceManager.GetString("checkBoxMakeUnLabeledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义字体.
        /// </summary>
        public static string checkBoxSetFont {
            get {
                return ResourceManager.GetString("checkBoxSetFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义字号.
        /// </summary>
        public static string checkBoxSetFontSize {
            get {
                return ResourceManager.GetString("checkBoxSetFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用指定类型图源.
        /// </summary>
        public static string checkBoxUseOtherFileType {
            get {
                return ResourceManager.GetString("checkBoxUseOtherFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除所有标签吗！？.
        /// </summary>
        public static string clear_all_label_question {
            get {
                return ResourceManager.GetString("clear_all_label_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译.
        /// </summary>
        public static string default_file_name {
            get {
                return ResourceManager.GetString("default_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件StartBlocks丢失.
        /// </summary>
        public static string error_file_startblocks_lost {
            get {
                return ResourceManager.GetString("error_file_startblocks_lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件版本太高，无法使用本版本编辑！.
        /// </summary>
        public static string error_file_version_over {
            get {
                return ResourceManager.GetString("error_file_version_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件失败.
        /// </summary>
        public static string error_openfilefail {
            get {
                return ResourceManager.GetString("error_openfilefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出(_E).
        /// </summary>
        public static string exitEToolStripMenuItem {
            get {
                return ResourceManager.GetString("exitEToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件设置.
        /// </summary>
        public static string FileSettingFrm_Text {
            get {
                return ResourceManager.GetString("FileSettingFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string fileToolStripLabel {
            get {
                return ResourceManager.GetString("fileToolStripLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件(_F).
        /// </summary>
        public static string fileToolStripMenuItem {
            get {
                return ResourceManager.GetString("fileToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助(_H).
        /// </summary>
        public static string helpAToolStripMenuItem {
            get {
                return ResourceManager.GetString("helpAToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出带标记图片.
        /// </summary>
        public static string ImageOutputFrm_Text {
            get {
                return ResourceManager.GetString("ImageOutputFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片管理(_I).
        /// </summary>
        public static string imageToolStripMenuItem {
            get {
                return ResourceManager.GetString("imageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件未保存，请先将文件存至与图片同文件夹下！.
        /// </summary>
        public static string input_images_need_save {
            get {
                return ResourceManager.GetString("input_images_need_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程及自动化.
        /// </summary>
        public static string labelAutodoTip {
            get {
                return ResourceManager.GetString("labelAutodoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (动作组名).
        /// </summary>
        public static string labelAutoGroupActionTip {
            get {
                return ResourceManager.GetString("labelAutoGroupActionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string labelComment {
            get {
                return ResourceManager.GetString("labelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换条目(Ctrl+Enter,),快捷短语(Alt+A).
        /// </summary>
        public static string labelCtrlEnterTip {
            get {
                return ResourceManager.GetString("labelCtrlEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认格式.
        /// </summary>
        public static string labelDefaultFormatTip {
            get {
                return ResourceManager.GetString("labelDefaultFormatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忽略文件.
        /// </summary>
        public static string labelFolderFile {
            get {
                return ResourceManager.GetString("labelFolderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组设置.
        /// </summary>
        public static string labelGroup {
            get {
                return ResourceManager.GetString("labelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 包含文件.
        /// </summary>
        public static string labelIncludedFile {
            get {
                return ResourceManager.GetString("labelIncludedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出标号(1、2、3…).
        /// </summary>
        public static string LabelNumCheckBox {
            get {
                return ResourceManager.GetString("LabelNumCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出格式.
        /// </summary>
        public static string labelOutputFormat {
            get {
                return ResourceManager.GetString("labelOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出项目.
        /// </summary>
        public static string labelOutputItemTip {
            get {
                return ResourceManager.GetString("labelOutputItemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放比例.
        /// </summary>
        public static string labelZoom {
            get {
                return ResourceManager.GetString("labelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言:.
        /// </summary>
        public static string languageblock {
            get {
                return ResourceManager.GetString("languageblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除(_D).
        /// </summary>
        public static string listview_menustrip_del {
            get {
                return ResourceManager.GetString("listview_menustrip_del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片管理.
        /// </summary>
        public static string ManageImageFrm_Text {
            get {
                return ResourceManager.GetString("ManageImageFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建翻译(_N).
        /// </summary>
        public static string newToolStripMenuItem {
            get {
                return ResourceManager.GetString("newToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不要在编辑后关闭此文件.
        /// </summary>
        public static string notCloseFileCheckBox {
            get {
                return ResourceManager.GetString("notCloseFileCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加头尾标志(startN、endN) .
        /// </summary>
        public static string notHeadFootSignCheckBox {
            get {
                return ResourceManager.GetString("notHeadFootSignCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加头尾标志(startN、endN) 以便使用动作.
        /// </summary>
        public static string notLabelNumCheckBox {
            get {
                return ResourceManager.GetString("notLabelNumCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开翻译(_O).
        /// </summary>
        public static string openToolStripMenuItem {
            get {
                return ResourceManager.GetString("openToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出已终止.
        /// </summary>
        public static string output_aborted {
            get {
                return ResourceManager.GetString("output_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出完毕.
        /// </summary>
        public static string output_complete {
            get {
                return ResourceManager.GetString("output_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出失败.
        /// </summary>
        public static string output_fail {
            get {
                return ResourceManager.GetString("output_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出带标记图片(_O).
        /// </summary>
        public static string outputAllToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputAllToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string outputButton {
            get {
                return ResourceManager.GetString("outputButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出Photoshop脚本(_P).
        /// </summary>
        public static string outputPhotoshopScriptToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputPhotoshopScriptToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出(_O).
        /// </summary>
        public static string outputPToolStripMenuItem {
            get {
                return ResourceManager.GetString("outputPToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出PS脚本.
        /// </summary>
        public static string OutputScriptFrm_Text {
            get {
                return ResourceManager.GetString("OutputScriptFrm.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成成功 脚本文件已保存在同一目录下：auto_label_for_photoshop.jsx \n 使用方法：1.直接拖进Photoshop中；或&quot;文件-脚本-浏览&quot;，选中脚本 \n2.选择图片所在目录.
        /// </summary>
        public static string ps_output_complete {
            get {
                return ResourceManager.GetString("ps_output_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        public static string save_complete {
            get {
                return ResourceManager.GetString("save_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件已修改，是否保存？.
        /// </summary>
        public static string save_question {
            get {
                return ResourceManager.GetString("save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译另存为(_S).
        /// </summary>
        public static string saveAsDToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveAsDToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存翻译(_S).
        /// </summary>
        public static string saveProjectSToolStripMenuItem {
            get {
                return ResourceManager.GetString("saveProjectSToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择图片文件夹。\n程序将为您在目录下自动创建翻译文本文件。.
        /// </summary>
        public static string tip_chose_photo_dir {
            get {
                return ResourceManager.GetString("tip_chose_photo_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件已保存为：{0}.
        /// </summary>
        public static string tip_new_file_be_saved {
            get {
                return ResourceManager.GetString("tip_new_file_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注里不能以&apos;-&apos;作为单独一行.
        /// </summary>
        public static string tip_setting_comment {
            get {
                return ResourceManager.GetString("tip_setting_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请以正确的格式设置分组，每行一组，分组数量为1-9组.
        /// </summary>
        public static string tip_setting_group {
            get {
                return ResourceManager.GetString("tip_setting_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认删除选中的标签吗?.
        /// </summary>
        public static string tip_sure_del_label {
            get {
                return ResourceManager.GetString("tip_sure_del_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浏览模式(_Q).
        /// </summary>
        public static string toolStripButton_BrowseMode {
            get {
                return ResourceManager.GetString("toolStripButton_BrowseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审校模式(_R).
        /// </summary>
        public static string toolStripButton_CheckMode {
            get {
                return ResourceManager.GetString("toolStripButton_CheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体增大.
        /// </summary>
        public static string toolStripButton_EditBig {
            get {
                return ResourceManager.GetString("toolStripButton_EditBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label模式(_W).
        /// </summary>
        public static string toolStripButton_EditLabelMode {
            get {
                return ResourceManager.GetString("toolStripButton_EditLabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体减小.
        /// </summary>
        public static string toolStripButton_EditSmall {
            get {
                return ResourceManager.GetString("toolStripButton_EditSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件设置.
        /// </summary>
        public static string toolStripButton_FileSetting {
            get {
                return ResourceManager.GetString("toolStripButton_FileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏窗口(_T).
        /// </summary>
        public static string toolStripButton_HideWindow {
            get {
                return ResourceManager.GetString("toolStripButton_HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 录入模式(_E).
        /// </summary>
        public static string toolStripButton_InputMode {
            get {
                return ResourceManager.GetString("toolStripButton_InputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框内.
        /// </summary>
        public static string toolStripButton_zoomIn {
            get {
                return ResourceManager.GetString("toolStripButton_zoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 框外.
        /// </summary>
        public static string toolStripButton_zoomOut {
            get {
                return ResourceManager.GetString("toolStripButton_zoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字键设置分类.
        /// </summary>
        public static string toolStripLabelTipSetCategory {
            get {
                return ResourceManager.GetString("toolStripLabelTipSetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示帮助(_H).
        /// </summary>
        public static string viewHelpHToolStripMenuItem {
            get {
                return ResourceManager.GetString("viewHelpHToolStripMenuItem", resourceCulture);
            }
        }
    }
}
