title: LabelPlus Next 文档
description: 使用指南、上传流程、解析规则、协作与性能优化
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  input: GFM
# 站点设置
# 自定义域名部署在根路径：
url: "https://doc.seastarss.cn"
baseurl: ""
